### ISSUE TITLE
Question: inclusion in addons svn?

### ISSUE THREAD

**Issue by awickert** [petrasovaa/r.patch.smooth#2]
Hi Anna --

My research group has used this module and it is really great! Have you thought of maintaining a parallel version in the GRASS svn repository so it shows up via g.extension?

Thanks for writing it and making it public!

**Comment by petrasovaa** [comment]
Thanks for the feedback, great you are using it. Yes, I should put it in svn, putting it on my TODO list!

**Comment by awickert** [comment]
Excellent!

**Comment by petrasovaa** [comment]
Should be available from grass addons now.
